### ISSUE TITLE
Can't build from source ubuntu20.04 arm64 

### ISSUE THREAD

**Issue by darzok0914** [Morpheus636/zeal-cli#67]
### Describe the Bug

I'm trying the build from source on ubuntu arm64. 
I read the instructions but the makefile is not working because it's trying to delete a directory that doesn't exist and so it fails.
I tried to fix it but I had other errors, I lost track.

I looked into the CI to see how it was built.  I am not a python dev and I don't know poetry.

### Steps to Reproduce the Bug

```bash
cd /tmp
git clone https://github.com/Morpheus636/zeal-cli.git
cd zeal-cli
git checkout v1.2.0
poetry env use 3.10
poetry install
make build
zeal-cli
```

```bash
Traceback (most recent call last):
  File "zeal_cli/__main__.py", line 5, in <module>
ImportError: attempted relative import with no known parent package
[87166] Failed to execute script '__main__' due to unhandled exception!   
```

### OS

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by Morpheus636** [comment]
Hmmm, What if you don't run `poetry env use 3.10`? Poetry should create and use a venv for you on it's own.

**Comment by darzok0914** [comment]
ok so it seems that I must I have messed up from previous trials, all I had to do was copying the binary from the dist folder into the ~/.local/bin/

**Comment by Morpheus636** [comment]
Ok, great! Did `make linux-install` not work for you? It should've done that automatically.
